# fly.toml app configuration file generated for content-moderator-api on 2025-01-08T16:53:03-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'content-moderator-api'
primary_region = 'sjc'

[build]
[build.args]
GO_VERSION = '1.22.1'

[env]
PORT = '8080'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
